version: "3.7"
services:
  db:
    image: postgres:14-alpine
    hostname: db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: 1223
      POSTGRES_DB: local
  redis: 
    image: redis
    hostname: redis
    ports: 
      - "6379:6379"